### PR TITLE
Changed dataset compression method, now it's lighter, and tests pass much faster

### PR DESCRIPTION
**Pull request by Dopervigest**

### CODE REVIEW

**Comment by Dopervigest** [comment]
The previous archive size was 45,6 mb, now it's 9

**Review by KonstantinUshenin — DISMISSED** [review]
ok

**Review by KonstantinUshenin — CHANGES_REQUESTED** [review]
Could you add some tests for new functions?

**Comment by Dopervigest** [comment]
new functions replaced the previous ones, they are tested with existing tests

**Review by KonstantinUshenin — APPROVED** [review]

**Pull request merged**
