### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by maksim-dzhigil**

### CODE REVIEW

**Comment by maksim-dzhigil** [comment]
The tests are still broken but now there are no NameError's.

image

I also found out that there are no explore() and initialization() methods in the space2.abstracts module but they are called (and they are in space.abstract).
I hope this helps!

**Comment by KonstantinUshenin** [comment]
BROKEN_test_space2_OLD uses Object, not Object3D.

**Review by KonstantinUshenin — COMMENTED** [review]
ok

**Review by KonstantinUshenin — APPROVED** [review]
ok

**Pull request merged**
